# Generated by Django 5.0.14 on 2026-05-14 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('kind', models.CharField(choices=[('income', '收入'), ('expense', '支出')], db_index=True, max_length=20, verbose_name='类型')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科目分类',
                'verbose_name_plural': '科目分类',
                'ordering': ('kind', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('transaction_type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], db_index=True, max_length=20, verbose_name='收支类型')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正数，单位与记账本位币一致', max_digits=12, verbose_name='金额')),
                ('account_name', models.CharField(max_length=200, verbose_name='账户名称')),
                ('is_reconciled', models.BooleanField(db_index=True, default=False, verbose_name='已对账')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收支明细',
                'verbose_name_plural': '收支明细',
                'ordering': ('-date', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'kind'), name='finance_category_unique_name_kind'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category', verbose_name='科目'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
