# Generated by Django 5.0.14 on 2026-05-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
            ],
            options={
                'verbose_name': '支出明细',
                'verbose_name_plural': '支出明细',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
            ],
            options={
                'verbose_name': '收入明细',
                'verbose_name_plural': '收入明细',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.transaction',),
        ),
    ]
