# Generated by Django 5.0.14 on 2026-05-15 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_income_expense_proxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='项目编码')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流水标签',
                'verbose_name_plural': '流水标签',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='摘要/备注'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='finance.tag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='finance_attachments/%Y/%m/', verbose_name='文件')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.transaction', verbose_name='流水')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '流水凭证附件',
                'verbose_name_plural': '流水凭证附件',
                'ordering': ('pk',),
            },
        ),
    ]
