# Generated by Django 5.0.14 on 2026-05-15 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance', '0004_project_tag_transaction_note_transaction_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('code',), 'permissions': [('view_all_projects', '可查看全部项目（忽略可见分组）')], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date', '-pk'), 'permissions': [('view_all_finance_transactions', '可查看全部财务流水（忽略项目/往来可见范围）')], 'verbose_name': '收支明细', 'verbose_name_plural': '收支明细'},
        ),
        migrations.AddField(
            model_name='project',
            name='visibility_groups',
            field=models.ManyToManyField(blank=True, help_text='不选则所有可查看项目的用户均可见；选择后仅所选分组内的用户可见。', related_name='finance_projects_visible', to='auth.group', verbose_name='可见分组'),
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='单位编码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('kind', models.CharField(choices=[('customer', '客户'), ('vendor', '供应商'), ('both', '客户与供应商')], db_index=True, max_length=20, verbose_name='类型')),
                ('tax_id', models.CharField(blank=True, max_length=40, verbose_name='税号/统一社会信用代码')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=40, verbose_name='电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('billing_address', models.TextField(blank=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('visibility_groups', models.ManyToManyField(blank=True, help_text='不选则所有可查看往来单位的用户均可见；选择后仅所选分组内的用户可见。', related_name='finance_counterparties_visible', to='auth.group', verbose_name='可见分组')),
            ],
            options={
                'verbose_name': '往来单位',
                'verbose_name_plural': '往来单位',
                'ordering': ('code',),
                'permissions': [('view_all_counterparties', '可查看全部往来单位（忽略可见分组）')],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.counterparty', verbose_name='往来单位'),
        ),
    ]
