# Generated by Django 5.0.14 on 2026-05-15 21:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance', '0005_counterparty_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='应收单号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('issue_date', models.DateField(db_index=True, verbose_name='立账/开票日期')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='约定收款日')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='应收金额')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='由收款核销累加；当前阶段可在后台由管理员手工调整。', max_digits=14, verbose_name='已收金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '待收款'), ('partial', '部分收款'), ('paid', '已结清'), ('void', '已作废')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='finance.counterparty', verbose_name='客户')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('visibility_groups', models.ManyToManyField(blank=True, help_text='不选则所有可查看应收的用户均可见；选择后仅所选分组内的用户可见。', related_name='finance_ar_invoices_visible', to='auth.group', verbose_name='可见分组')),
            ],
            options={
                'verbose_name': '应收账单',
                'verbose_name_plural': '应收账单',
                'ordering': ('-issue_date', '-pk'),
                'permissions': [('view_all_arinvoices', '可查看全部应收账单（忽略可见分组）')],
            },
        ),
        migrations.AddConstraint(
            model_name='arinvoice',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__lte', models.F('amount_total'))), name='finance_ar_amount_paid_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='arinvoice',
            constraint=models.CheckConstraint(check=models.Q(('amount_total__gt', 0)), name='finance_ar_amount_total_positive'),
        ),
    ]
