# Generated by Django 5.0.14 on 2026-05-15 22:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_ar_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='由收款核销明细自动汇总；不在此手工改数。', max_digits=14, verbose_name='已收金额'),
        ),
        migrations.CreateModel(
            name='ARPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='核销金额')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ar_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finance.arinvoice', verbose_name='应收账单')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_payment_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_payment_allocations', to='finance.transaction', verbose_name='收款流水')),
            ],
            options={
                'verbose_name': '应收核销记录',
                'verbose_name_plural': '应收核销记录',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='arpaymentallocation',
            constraint=models.UniqueConstraint(fields=('ar_invoice', 'transaction'), name='finance_ar_payment_alloc_unique_invoice_tx'),
        ),
        migrations.AddConstraint(
            model_name='arpaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='finance_ar_payment_alloc_amount_positive'),
        ),
    ]
