# Generated by Django 5.0.14 on 2026-05-18 20:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance', '0007_ar_payment_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='应付单号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('issue_date', models.DateField(db_index=True, verbose_name='立账日期')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='约定付款日')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='应付金额')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='由付款核销明细自动汇总；不在此手工改数。', max_digits=14, verbose_name='已付金额')),
                ('approval_status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], db_index=True, default='draft', max_length=20, verbose_name='审批状态')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '待付款'), ('partial', '部分付款'), ('paid', '已结清'), ('void', '已作废')], db_index=True, default='draft', max_length=20, verbose_name='付款状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='finance.counterparty', verbose_name='供应商')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('visibility_groups', models.ManyToManyField(blank=True, help_text='不选则所有可查看应付的用户均可见；选择后仅所选分组内的用户可见。', related_name='finance_ap_invoices_visible', to='auth.group', verbose_name='可见分组')),
            ],
            options={
                'verbose_name': '应付账单',
                'verbose_name_plural': '应付账单',
                'ordering': ('-issue_date', '-pk'),
                'permissions': [('view_all_apinvoices', '可查看全部应付账单（忽略可见分组）'), ('approve_apinvoice', '可审批应付账单')],
            },
        ),
        migrations.CreateModel(
            name='APPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='核销金额')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ap_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finance.apinvoice', verbose_name='应付账单')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_payment_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_payment_allocations', to='finance.transaction', verbose_name='付款流水')),
            ],
            options={
                'verbose_name': '应付核销记录',
                'verbose_name_plural': '应付核销记录',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='apinvoice',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__lte', models.F('amount_total'))), name='finance_ap_amount_paid_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='apinvoice',
            constraint=models.CheckConstraint(check=models.Q(('amount_total__gt', 0)), name='finance_ap_amount_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='appaymentallocation',
            constraint=models.UniqueConstraint(fields=('ap_invoice', 'transaction'), name='finance_ap_payment_alloc_unique_invoice_tx'),
        ),
        migrations.AddConstraint(
            model_name='appaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='finance_ap_payment_alloc_amount_positive'),
        ),
    ]
