# Generated by Django 5.0.14 on 2026-05-18 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_ap_invoice_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='与系统内收支流水的「账户名称」一致，便于后续对账匹配。', max_length=200, verbose_name='账户名称')),
                ('source', models.CharField(choices=[('bank_csv', '银行 CSV'), ('alipay', '支付宝账单'), ('wechat', '微信支付账单'), ('other', '其他')], db_index=True, default='bank_csv', max_length=20, verbose_name='来源')),
                ('file', models.FileField(upload_to='bank_statements/%Y/%m/', verbose_name='账单文件')),
                ('status', models.CharField(choices=[('pending', '待导入'), ('success', '导入成功'), ('partial', '部分成功'), ('failed', '导入失败')], db_index=True, default='pending', max_length=20, verbose_name='导入状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='文件行数')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='成功导入')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='解析失败')),
                ('error_log', models.TextField(blank=True, verbose_name='错误日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_batches', to=settings.AUTH_USER_MODEL, verbose_name='导入人')),
            ],
            options={
                'verbose_name': '银行账单导入',
                'verbose_name_plural': '银行账单导入',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField(db_index=True, verbose_name='交易日期')),
                ('transaction_type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], db_index=True, max_length=20, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='流水号/参考号')),
                ('counterparty_hint', models.CharField(blank=True, max_length=200, verbose_name='对方户名')),
                ('source_row_number', models.PositiveIntegerField(default=0, verbose_name='源文件行号')),
                ('match_status', models.CharField(choices=[('unmatched', '未匹配'), ('matched', '已匹配'), ('ignored', '已忽略')], db_index=True, default='unmatched', max_length=20, verbose_name='匹配状态')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.bankstatementbatch', verbose_name='导入批次')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_lines', to='finance.transaction', verbose_name='已匹配系统流水')),
            ],
            options={
                'verbose_name': '银行账单明细',
                'verbose_name_plural': '银行账单明细',
                'ordering': ('-line_date', '-pk'),
                'indexes': [models.Index(fields=['batch', 'match_status'], name='finance_ban_batch_i_99bd5b_idx')],
            },
        ),
    ]
