# Generated by Django 5.0.14 on 2026-05-18 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_bank_statement_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bank_fee', '银行手续费'), ('rounding', '尾差'), ('unrecorded_bank', '有账未记账（银行有、系统无）'), ('unrecorded_book', '已记账未到账（系统有、银行无）'), ('other', '其他')], db_index=True, max_length=30, verbose_name='差异类型')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正数，表示需调整或说明的金额规模。', max_digits=14, verbose_name='差异金额')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('adjustment_category', models.ForeignKey(blank=True, help_text='生成调整流水时使用的科目；保存后若勾选「生成调整流水」则必填。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_variances', to='finance.category', verbose_name='调整科目')),
                ('adjustment_transaction', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_variance', to='finance.transaction', verbose_name='调整流水')),
                ('bank_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='finance.bankstatementline', verbose_name='银行明细')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='finance.bankstatementbatch', verbose_name='导入批次')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_variances_created', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_variances', to='finance.transaction', verbose_name='系统流水')),
            ],
            options={
                'verbose_name': '对账差异',
                'verbose_name_plural': '对账差异',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
