# Generated by Django 5.0.14 on 2026-05-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_reconciliation_variance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('kind', 'sort_order', 'name'), 'permissions': [('manage_database', '备份与还原数据库')], 'verbose_name': '科目分类', 'verbose_name_plural': '科目分类'},
        ),
    ]
