#!/usr/bin/env python3
"""Fill empty msgstr entries in locale/zh_Hans/LC_MESSAGES/django.po."""
from __future__ import annotations

import polib

PO_PATH = "locale/zh_Hans/LC_MESSAGES/django.po"

# English msgid -> Simplified Chinese (admin / finance UI)
ZH = {
    "Sort Order": "排序",
    "Created At": "创建时间",
    "Updated At": "更新时间",
    "Account Category": "科目分类",
    "Account Categories": "科目分类",
    "Unit Code": "单位编码",
    "Tax ID / Unified Social Credit Code": "税号/统一社会信用代码",
    "Contact Name": "联系人",
    "Phone": "电话",
    "Address": "地址",
    "Remark": "备注",
    "Visible Groups": "可见分组",
    "If empty, visible to all users who can view counterparties; if set, only users in selected groups can see this record.": "不选则所有可查看往来单位的用户均可见；选择后仅所选分组内的用户可见。",
    "Counterparty": "往来单位",
    "Can view all counterparties (ignore visibility groups)": "可查看全部往来单位（忽略可见分组）",
    "Project Code": "项目编码",
    "Project Name": "项目名称",
    "If empty, visible to all users who can view projects; if set, only users in selected groups can see this record.": "不选则所有可查看项目的用户均可见；选择后仅所选分组内的用户可见。",
    "Can view all projects (ignore visibility groups)": "可查看全部项目（忽略可见分组）",
    "Tag": "标签",
    "Transaction Tag": "流水标签",
    "Transaction Tags": "流水标签",
    "Transaction Type": "收支类型",
    "Positive amount in base currency": "正数，单位与记账本位币一致",
    "Account Name": "账户名称",
    "Description / Note": "摘要/备注",
    "Reconciled": "已对账",
    "Created By": "创建人",
    "Transaction": "收支明细",
    "Can view all finance transactions (ignore project/counterparty visibility)": "可查看全部财务流水（忽略项目/往来可见范围）",
    "The selected category type must match the transaction type.": "所选科目类型必须与收支类型一致。",
    "Amount must be greater than 0.": "金额必须大于 0。",
    "File": "文件",
    "Caption": "说明",
    "Uploaded At": "上传时间",
    "Uploaded By": "上传人",
    "Transaction Attachment": "流水附件",
    "Transaction Attachments": "流水附件",
    "Draft": "草稿",
    "Open": "未结清",
    "Partially Paid": "部分结清",
    "Paid": "已结清",
    "Void": "作废",
    "Pending Approval": "待审批",
    "Approved": "已批准",
    "Rejected": "已驳回",
    "Summarize income and expense by period, category, and project.": "按期间、科目与项目汇总收入与支出，查看净利润。",
    "Operating cash inflows, outflows, and net by account.": "期间经营现金流入、流出及净额，按账户名称分列。",
    "Cash, AR, AP, and cumulative surplus (lightweight).": "货币资金、应收、应付与累计盈余（轻量口径）。",
    "Expected receipts and payments by invoice due dates.": "按应收/应付约定到期日汇总预计收付款。",
    "Open report": "打开报表",
    "Income/expense trend and category share": "收支趋势与分类占比",
    "Income Entry": "收入明细",
    "Income Entries": "收入明细",
    "Expense Entry": "支出明细",
    "Expense Entries": "支出明细",
    "Home": "首页",
    "Language": "语言",
    "Dashboard": "工作台",
    "Overview": "财务概览",
    "Reports": "财务报表",
    "Transactions": "日常记账",
    "Master data": "基础资料",
    "AR / AP": "应收应付",
    "Bank reconciliation": "银行对账",
    "Audit": "审计中心",
    "System": "系统管理",
    "Report center": "报表中心",
    "Finance dashboard": "财务看板",
    "Profit & loss": "损益表",
    "Cash flow statement": "现金流量表",
    "Balance sheet": "资产负债表",
    "Cash flow forecast": "现金流预测",
    "Income entries": "收入明细",
    "Expense entries": "支出明细",
    "Categories": "科目分类",
    "Projects": "项目",
    "Tags": "流水标签",
    "Counterparties": "往来单位",
    "AR invoices": "应收账单",
    "AP invoices": "应付账单",
    "Bank statement import": "银行账单导入",
    "Bank statement lines": "银行账单明细",
    "Reconciliation variances": "对账差异",
    "Audit log": "操作日志",
    "System settings": "系统设置",
    "Groups": "用户组",
    "Apply": "查询",
    "All": "全部",
    "Search": "搜索",
    "No data": "无数据",
    "Income": "收入",
    "Expense": "支出",
    "Project": "项目",
    "Category": "科目",
    "Amount": "金额",
    "Date": "日期",
    "Previous": "上一页",
    "Next": "下一页",
    "Balance": "结余",
    "Total income": "总收入",
    "Total expense": "总支出",
    "Net profit": "净利润",
    "Claa Finance": "轻量财务管理系统",
    "Finance Admin": "财务管理",
    # --- remaining empty msgids (finance AR/AP, bank recon, imports, reports, admin) ---
    "%(name)s object with primary key %(key)r does not exist.": "主键为 %(key)r 的 %(name)s 对象不存在。",
    "If empty, visible to all users who can view counterparties; if set, only users in selected groups can view.": "不选则所有可查看往来单位的用户均可见；选择后仅所选分组内的用户可见。",
    "If empty, visible to all users who can view projects; if set, only users in selected groups can view.": "不选则所有可查看项目的用户均可见；选择后仅所选分组内的用户可见。",
    "AR Invoice Number": "应收账单编号",
    "Title": "标题",
    "Issue Date": "开票日期",
    "Due Date": "到期日",
    "Total Amount Receivable": "应收总额",
    "Amount Received": "已收金额",
    "Automatically summarized from payment allocations; do not edit manually.": "由收款/付款分配自动汇总；请勿手工修改。",
    "If empty, visible to all users who can view AR invoices; if set, only users in selected groups can view.": "不选则所有可查看应收账单的用户均可见；选择后仅所选分组内的用户可见。",
    "AR Invoice": "应收账单",
    "AR Invoices": "应收账单",
    "Can view all AR invoices (ignore visibility groups)": "可查看全部应收账单（忽略可见分组）",
    "AR invoices can only be linked to counterparties of type Customer or Customer and Vendor.": "应收账单只能关联类型为「客户」或「客户兼供应商」的往来单位。",
    "Amount received cannot exceed total receivable.": "已收金额不能超过应收总额。",
    "Receipt Transaction": "收款流水",
    "Allocation Amount": "分配金额",
    "AR Payment Allocation": "应收收款分配",
    "AR Payment Allocations": "应收收款分配",
    "allocation": "分配",
    "Only income transactions can be allocated to AR invoices.": "仅可将收入流水分配至应收账单。",
    "Transaction counterparty must match the AR invoice customer.": "流水往来单位必须与应收账单客户一致。",
    "Total allocations cannot exceed invoice amount.": "分配总额不能超过账单金额。",
    "Total allocated amount exceeds the transaction amount.": "已分配总额超过流水金额。",
    "AP Invoice Number": "应付账单编号",
    "Total Amount Payable": "应付总额",
    "Amount Paid": "已付金额",
    "Approval Status": "审批状态",
    "Payment Status": "付款状态",
    "If empty, visible to all users who can view AP invoices; if set, only users in selected groups can view.": "不选则所有可查看应付账单的用户均可见；选择后仅所选分组内的用户可见。",
    "AP Invoice": "应付账单",
    "AP Invoices": "应付账单",
    "Can view all AP invoices (ignore visibility groups)": "可查看全部应付账单（忽略可见分组）",
    "Can approve AP invoices": "可审批应付账单",
    "AP invoices can only be linked to counterparties of type Vendor or Customer and Vendor.": "应付账单只能关联类型为「供应商」或「客户兼供应商」的往来单位。",
    "Amount paid cannot exceed total payable.": "已付金额不能超过应付总额。",
    "Payment Transaction": "付款流水",
    "AP Payment Allocation": "应付付款分配",
    "AP Payment Allocations": "应付付款分配",
    "Only approved AP invoices can receive payment allocations.": "仅已批准的应付账单可接收付款分配。",
    "Only expense transactions can be allocated to AP invoices.": "仅可将支出流水分配至应付账单。",
    "Transaction counterparty must match the AP invoice vendor.": "流水往来单位必须与应付账单供应商一致。",
    "Bank CSV": "银行 CSV",
    "Alipay Statement": "支付宝账单",
    "WeChat Pay Statement": "微信支付账单",
    "Other": "其他",
    "Pending Import": "待导入",
    "Import Successful": "导入成功",
    "Partially Successful": "部分成功",
    "Import Failed": "导入失败",
    "Unmatched": "未匹配",
    "Matched": "已匹配",
    "Ignored": "已忽略",
    "Must match the account name on system transactions for reconciliation.": "须与系统流水中的账户名称一致，以便对账。",
    "Source": "来源",
    "Statement File": "账单文件",
    "Import Status": "导入状态",
    "Total Rows": "总行数",
    "Imported Rows": "已导入行数",
    "Failed Rows": "失败行数",
    "Error Log": "错误日志",
    "Imported By": "导入人",
    "Imported At": "导入时间",
    "Bank Statement Import": "银行账单导入",
    "Bank Statement Imports": "银行账单导入",
    "Import Batch": "导入批次",
    "Transaction Date": "交易日期",
    "Direction": "方向",
    "Description": "摘要",
    "Reference Number": "参考号",
    "Counterparty Name": "对方户名",
    "Source Row Number": "源文件行号",
    "Match Status": "匹配状态",
    "Matched Transaction": "已匹配流水",
    "Bank Statement Line": "银行账单明细",
    "Bank Statement Lines": "银行账单明细",
    "Bank Fee": "银行手续费",
    "Rounding Difference": "尾差",
    "Unrecorded in Books (bank has, system does not)": "账未记（银行有、系统无）",
    "Unrecorded in Bank (system has, bank does not)": "银行未记（系统有、银行无）",
    "System Transaction": "系统流水",
    "Variance Type": "差异类型",
    "Variance Amount": "差异金额",
    "Positive amount representing the scale of adjustment or explanation.": "正数，表示调整或说明的规模。",
    "Note": "说明",
    "Adjustment Category": "调整科目",
    "Category used when generating an adjustment transaction; required if creating one.": "生成调整流水时使用的科目；若创建调整流水则必填。",
    "Adjustment Transaction": "调整流水",
    "Resolved": "已处理",
    "Recorded By": "登记人",
    "Recorded At": "登记时间",
    "Reconciliation Variance": "对账差异",
    "Reconciliation Variances": "对账差异",
    "At least one of import batch, bank line, or system transaction is required.": "导入批次、银行明细、系统流水至少须填写一项。",
    "Variance amount must be greater than 0.": "差异金额必须大于 0。",
    "Bank line does not belong to the selected import batch.": "该银行明细不属于所选导入批次。",
    "Income Transaction": "收入流水",
    "Income Transactions": "收入流水",
    "Expense Transaction": "支出流水",
    "Expense Transactions": "支出流水",
    "Transaction type is required": "须填写收支类型",
    "Unrecognized transaction type: %(raw)s": "无法识别的收支类型：%(raw)s",
    "Project code": "项目编码",
    "Counterparty code": "往来单位编码",
    "Row %(row)s: type does not match this list (%(label)s).": "第 %(row)s 行：类型与本列表（%(label)s）不符。",
    "Category name is required": "须填写科目名称",
    "Row %(row)s: no active category “%(name)s” for type %(kind)s": "第 %(row)s 行：类型 %(kind)s 下无有效科目「%(name)s」",
    "Amount is required": "须填写金额",
    "Invalid amount: %(raw)s": "无效金额：%(raw)s",
    "Amount must be greater than zero": "金额必须大于零",
    "Row %(row)s: unknown active project code “%(code)s”": "第 %(row)s 行：未知有效项目编码「%(code)s」",
    "Row %(row)s: unknown active counterparty code “%(code)s”": "第 %(row)s 行：未知有效往来单位编码「%(code)s」",
    "Row %(row)s: unknown tag “%(name)s”. Create it in admin first.": "第 %(row)s 行：未知标签「%(name)s」，请先在后台创建。",
    "Date is required": "须填写日期",
    "Invalid date: %(raw)s": "无效日期：%(raw)s",
    "Account name is required": "须填写账户名称",
    "Balance sheet · cash detail": "资产负债表 · 货币资金明细",
    "Cash flow forecast · invoice details": "现金流预测 · 账单明细",
    "Enter a username and password.": "请输入用户名和密码。",
    "Django site admin": "Django 站点管理",
    "Django administration": "Django 管理后台",
    "History": "历史",
    "View on site": "在站点查看",
    "Please correct the error below.": "请修正以下错误。",
    "Please correct the errors below.": "请修正以下错误。",
    "\n    Page %(page)s of %(total)s (%(count)s rows)\n    ": "\n    第 %(page)s / %(total)s 页（共 %(count)s 行）\n    ",
    "Lightweight view: cash is cumulative net inflow per account name; AR/AP are open invoice balances; equity is cumulative net from entries. Assets, liabilities, and equity each have a tab.": "轻量口径：货币资金按账户名称累计净流入；应收/应付为未结清账单余额；权益为流水累计净利。资产、负债、权益各一标签页。",
    "No projects defined yet": "尚未定义项目",
    "Projects are maintained under": "项目维护入口：",
    "Master data → Projects": "基础资料 → 项目",
    ".": "。",
    "Project filter applies to cash and cumulative net from entries only; AR/AP are not split by project.": "项目筛选仅作用于货币资金与流水累计净利；应收/应付不按项目拆分。",
    "Summary rows (fixed count). Columns: category, detail drill-down (cash by account), amount.": "汇总行（固定行数）。列：类别、明细下钻（货币资金按账户）、金额。",
    "Cash detail": "货币资金明细",
    "Cumulative net inflow per account name as of %(as_of)s; paginated because row count varies.": "截至 %(as_of)s 各账户名称累计净流入；行数不固定，分页展示。",
    "Total cash": "货币资金合计",
    "Account name": "账户名称",
    "Total": "合计",
    "Back to balance sheet": "返回资产负债表",
    "Lightweight: income/expense entries treated as operating cash; no investing/financing split.": "轻量口径：将收入/支出流水视为经营活动现金；不区分投资/筹资活动。",
    "; without projects, reports use the all-projects scope.": "；未定义项目时，报表按全部项目范围统计。",
    "Open AR/AP balances by due date. Three tabs; invoice details are paginated separately.": "按到期日汇总未结清应收/应付余额。三个标签页；账单明细分页展示。",
    "Expected net cash flow": "预计净现金流",
    "Invoice details": "账单明细",
    "Expected receipts": "预计收款",
    "Expected payments": "预计付款",
    "Open AR/AP invoices from %(date_from)s through %(date_to)s; paginated because row count varies.": "%(date_from)s 至 %(date_to)s 未结清应收/应付账单；行数不固定，分页展示。",
    "Management P&L from entries. Variable row counts per tab (income, expense, by project).": "基于流水的管理损益表。各标签页（收入、支出、分项目）行数不固定。",
    "All (including by project)": "全部（含分项目）",
    "Categories and projects": "科目与项目",
    "Period %(date_from)s — %(date_to)s; paginated because category row count varies.": "期间 %(date_from)s — %(date_to)s；科目行数不固定，分页展示。",
    "Period %(date_from)s — %(date_to)s; paginated because project row count varies.": "期间 %(date_from)s — %(date_to)s；项目行数不固定，分页展示。",
    "Database": "数据库",
    "Database file: <code>%(db)s</code>. Backups are stored under <code>backups/</code>. Restore replaces all data — back up first.": "数据库文件：<code>%(db)s</code>。备份保存在 <code>backups/</code> 目录。还原将覆盖全部数据，请先备份。",
    "Restore database": "还原数据库",
    "Or upload a .sqlite3 backup copied from another machine:": "或上传从其他机器复制的 .sqlite3 备份：",
    "No local backups yet. Upload a .sqlite3 file:": "尚无本地备份，请上传 .sqlite3 文件：",
    "PostgreSQL is in use. Use pg_dump, pg_restore, or your cloud console for backup/restore.": "当前使用 PostgreSQL，请使用 pg_dump、pg_restore 或云控制台进行备份/还原。",
    "%(counter)s result": ("%(counter)s 条结果", "%(counter)s 条结果"),
    "%(full_result_count)s total": "共 %(full_result_count)s 条",
    "Show all": "显示全部",
}


def _is_empty(entry: polib.POEntry) -> bool:
    if entry.msgid_plural:
        return not any(entry.msgstr_plural.values())
    return not entry.msgstr


def main():
    po = polib.pofile(PO_PATH)
    filled = 0
    for entry in po:
        if entry.obsolete or not entry.msgid or not _is_empty(entry):
            continue
        zh = ZH.get(entry.msgid)
        if not zh:
            continue
        if entry.msgid_plural and isinstance(zh, tuple):
            entry.msgstr_plural = {0: zh[0], 1: zh[1]}
        else:
            entry.msgstr = zh
        filled += 1
    po.save(PO_PATH)
    remaining = sum(1 for e in po if e.msgid and _is_empty(e) and not e.obsolete)
    print(f"filled {filled}, remaining empty {remaining}")


if __name__ == "__main__":
    main()
